### ISSUE TITLE
Unhandled Exception: FormatException: Unexpected character

### ISSUE THREAD

**Issue by alirezabhr** [viralvaghela/flutter_insta#19] opened 2021-07-27 19:57 UTC
Hi,
I got these errors.

[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: FormatException: Unexpected character (at character 1)
E/flutter (13105): <!DOCTYPE html>
E/flutter (13105): ^
E/flutter (13105): 
E/flutter (13105): #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1404:5)
E/flutter (13105): #1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1271:9)
E/flutter (13105): #2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:936:22)
E/flutter (13105): #3      _parseJson (dart:convert-patch/convert_patch.dart:40:10)
E/flutter (13105): #4      JsonDecoder.convert (dart:convert/json.dart:506:36)
E/flutter (13105): #5      JsonCodec.decode (dart:convert/json.dart:157:41)
E/flutter (13105): #6      FlutterInsta.getProfileData (package:flutter_insta/flutter_insta.dart:25:21)
E/flutter (13105): <asynchronous suspension>
E/flutter (13105): #7      _InstaDetailsState.setInstaDetails (package:linkish/ui/widgets/insta_detail.dart:24:5)
E/flutter (13105): <asynchronous suspension>
E/flutter (13105):

**Comment by DavideM12** [comment] 2021-07-28 08:53
Duplicate of #13

**Comment by viralvaghela** [comment] 2021-08-15 16:54
Duplicate of #13 , closing this issue

**Closed as completed by viralvaghela** 2021-08-15 16:54 UTC
